### ISSUE TITLE
Dashboard table overflowing Grafana panel

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/PowerMonitoring#10]
Running branch `master` (pruned and rebuilt post merge of `dashboard/basic-dashboard`)

On the Live (All) dashboard, sometimes the word energy and the value unit don't fit within the Grafana panel:
![image](https://github.com/DigitalShoestringSolutions/PowerMonitoring/assets/51968582/e8cc30a5-87b8-4ef2-b636-6e1be8ee5f7a)
I've not observed this before. Could it be intermittent, or introduced? None of the other dashboard appear to suffer from a similar issue.
Assuming it's always been there I'll look into editing the column width.

**Comment by Greg-Hawkridge** [comment]
This is an issue with how grafana maps to different screen sizes. There is nothing we can do to fix this consistently - we can add a Q&A to the community forum explaining how to make the panel bigger to make space when text overflows
