### ISSUE TITLE
Integration jitter

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/PowerMonitoring#34]
The integration is looking a bit unsteady. I tried shrinking the Time Buckets to enhance the issue and sure enough, buckets smaller than one minute make for very jittery Energy integrations, even when the power is steady:

![image](https://github.com/DigitalShoestringSolutions/PowerMonitoring/assets/51968582/fff1497b-78d4-4154-abb8-d7aa26845e01)

With a time bucket approaching the order of magnitude of the sample rate, I wouldn't be surprised at some counting jitter due to significant relative variation in how many samples fall in each bucket.

I suspect the integrator is vulnerable to this because it might be summing each (sample value x time until next sample). How can we handle the time window edge cases? 

Although related I feel this is a different problem to #7 .

**Comment by Greg-Hawkridge** [comment]
That will always be an issue - we should limit time bucket to being >10m

**Comment by tobyaharris** [comment]
Closing as accepting the status quo, refinement effort not worth it. Time bucket default options are already suitable.
