### ISSUE TITLE
WARNING:core.output:json_path $.power return no data and was ignored

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/PowerMonitoring#42]
On version `v1.0.1` in the logs of the current-sensing module I'm seeing the message `WARNING:core.output:json_path $.power return no data and was ignored` between every sample.

**Comment by tobyaharris** [comment]
check out L71 of pm_b_1ph_grove.toml and similar.

**Comment by Greg-Hawkridge** [comment]
remove $.power from mqtt message spec
